# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_wkt_sf <- function(sf) {
    .Call(`_hackspatialcpp_get_wkt_sf`, sf)
}

check_class_sf <- function(sf) {
    .Call(`_hackspatialcpp_check_class_sf`, sf)
}

something_with_raster <- function(raster) {
    .Call(`_hackspatialcpp_something_with_raster`, raster)
}

